#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : "Jupyter Book tutorial"  # The title of the book. Will be placed in the left navbar.
author                      : Alexis Olguin Baxman # The author of the book
copyright                   : "2026"  # Copyright year to be placed in the footer
logo                        : "static/pics/ANCP.png"  # A path to the book logo

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_edit_page_button      : True  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : True  # Whether to add a link to your repository button
  use_issues_button         : True  # Whether to add an "open an issue" butto
  
# ######################################################################################
repository:
  url                       : https://github.com/alexisbaxman/jupyter_template  # The URL to your book's repository
  path_to_book              :  "."
  branch                    : main  # Which branch of the repository should be used when creating links


