name: deploy-book 

on:
  push:
    branches:
      - main

env:
  BUILD_DIR: . 
  BUILD_OUTPUT: _build/html 
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
         python -m pip install -U pip 
          # Pin jb/sphinx to avoid breaking changes
          pip install "jupyter-book==1.0.0" "sphinx==7.4.7"
          # Your extras
          pip install sphinx-book-theme myst-nb ghp-import jupytext
          # lines before: add on 04.11
          pip install -r requirements.txt

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}/${{ env.BUILD_OUTPUT }}
          # path: "_build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
